export const LANGUAGE_CODES = {
  en: "English",
  zh: "Chinese",
  ja: "Japanese",
  de: "German",
  fr: "French",
  ru: "Russian",
  pt: "Portuguese",
  es: "Spanish",
  ko: "Korean",
  it: "Italian",
  en1: "Reserved",
  vi: "Vietnamese",
  nl: "Dutch",
  uk: "Ukrainian",
  ar: "Arabic",
  bn: "Bengali",
  "zh-hant": "Chinese (Traditional)",
  cs: "Czech",
  et: "Estonian",
  fi: "Finnish",
  el: "Greek",
  he: "Hebrew",
  hi: "Hindi",
  hu: "Hungarian",
  id: "Indonesian",
  ms: "Malay",
  fa: "Persian (Farsi)",
  pl: "Polish",
  ro: "Romanian",
  sv: "Swedish",
  ta: "Tamil",
  te: "Telugu",
  tl: "Tagalog",
  tr: "Turkish",
  da: "Danish",
  th: "Thai",
  "fr-ca": "Canadian French",
  "zh-yue": "Cantonese (Yue)",
};

// export const INDEXED_LANGUAGE_CODES = {
//   0: "en",
//   1: "zh",
//   2: "ja",
//   3: "de",
//   4: "fr",
//   5: "ru",
//   6: "pt",
//   7: "es",
//   8: "ko",
//   9: "it",
//   10: "en1",
//   11: "vi",
//   12: "nl",
//   13: "uk",
//   14: "ar",
//   15: "bn",
//   16: "zh-hant",
//   17: "cs",
//   18: "et",
//   19: "fi",
//   20: "el",
//   21: "he",
//   22: "hi",
//   23: "hu",
//   24: "id",
//   25: "ms",
//   26: "fa",
//   27: "pl",
//   28: "ro",
//   29: "sv",
//   30: "ta",
//   31: "te",
//   32: "tl",
//   33: "tr",
// };
